version: '3.9'

services:
  zundamon_bash_ui:
    container_name: zundamon-bash-ui
    ports:
      - '127.0.0.1:50021:50021'
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-0.14.5
    volumes:
      - type: bind
        source: ../conf/voicevox/presets.yaml
        target: /opt/voicevox_engine/presets.yaml

  zundamon_bash_ui_whisper:
    container_name: zundamon-bash-ui-whisper
    image: onerahmet/openai-whisper-asr-webservice:v1.1.1
    volumes:
      - type: bind
        source: ../output/
        target: /home/output/
    tty: true